# Assignment

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is, then write a code to print the data types of both the variables.
Yes, there is a difference. list_ is a Python list, while array_list is a NumPy array. Here's how to print the data types of both:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of both variables
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [4]:
# Data types of elements in list_
for element in list_:
    print(f"Data type of element '{element}' in list_: {type(element)}")

# Data types of elements in array_list
for element in array_list:
    print(f"Data type of element '{element}' in array_list: {type(element)}")


Data type of element '1' in list_: <class 'str'>
Data type of element '2' in list_: <class 'str'>
Data type of element '3' in list_: <class 'str'>
Data type of element '4' in list_: <class 'str'>
Data type of element '5' in list_: <class 'str'>
Data type of element '1' in array_list: <class 'numpy.str_'>
Data type of element '2' in array_list: <class 'numpy.str_'>
Data type of element '3' in array_list: <class 'numpy.str_'>
Data type of element '4' in array_list: <class 'numpy.str_'>
Data type of element '5' in array_list: <class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
 
array_list = np.array(object=list_, dtype=int)
Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so, then print the data types of each and every element.

Yes, there will be a difference. The elements in array_list will be converted to integers, while the elements in list_ remain strings.


array_list = np.array(object=list_, dtype=int)

# Data types of elements in list_
for element in list_:
    print(f"Data type of element '{element}' in list_: {type(element)}")

# Data types of elements in array_list
for element in array_list:
    print(f"Data type of element '{element}' in array_list: {type(element)}")


In [9]:
## Q4. Write a code to find the following characteristics of variable num_array:
## (i) Shape
## (ii) Size


import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Shape of num_array
print("Shape of num_array:", num_array.shape)

# Size of num_array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [10]:
## Q5. Write a code to create a NumPy array of a 3x3 matrix containing zeros only, using a NumPy array creation function.

import numpy as np

# Creating a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
## Q6. Create an identity matrix of shape (5,5) using NumPy functions.

import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
